name: Echo branch, author, and commit message

on: [push]

jobs:
  echo-branch-author-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Echo branch, author, and commit message
      run: |
        BRANCH=$(echo "${{ github.ref }}")
        BRANCH=${BRANCH#refs/heads/}
        COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.sha }})
        AUTHOR=${{ github.actor }}
        echo "Branch: $BRANCH"
        echo "Author: $AUTHOR"
        echo "Commit message: $COMMIT_MSG"
